# Generated by Django 5.0.7 on 2024-07-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0002_category_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='discription',
            field=models.TextField(default=None, verbose_name=1000),
        ),
    ]
