# Generated by Django 5.0.7 on 2024-07-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0003_menuitem_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='discription',
            new_name='description',
        ),
    ]
