# Generated by Django 5.0.7 on 2024-07-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0004_rename_discription_menuitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='inventory',
        ),
    ]
