# Generated by Django 5.0.7 on 2024-07-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0005_remove_menuitem_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='inventory',
            field=models.SmallIntegerField(default=10),
        ),
    ]
